name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tirate un job 1
        run: echo job 1

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Tirate un job 2
        run: echo job 2  

  job3:
    runs-on: ubuntu-latest
    environment: job3
    needs: job2
    #if: needs.job2.outputs.job2-status == 'true'
    steps:
      - name: Tirate un job 3
        run: echo job 3

  job4:
    runs-on: ubuntu-latest
    environment: job4
    needs: job2
    steps:
      - name: Tirate un job 4
        run: echo job 4

  job5:
    runs-on: ubuntu-latest
    environment: job5
    needs: job2
    steps:
      - name: Tirate un job 5
        run: echo job 5
               
  job6:
    runs-on: ubuntu-latest
    environment: job6
    needs: job2
    steps:
      - name: Tirate un job 6
        run: echo job                   