name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Tirate un echo
        run: echo job 1
  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: echo de jobs 
        run: echo job 2   

