name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
[
  { "name": "apple", "quantity": 1 },
  { "name": "orange", "quantity": 2 },
  { "name": "pear", "quantity": 1 }
]

jobs: 
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: echo de jobs 
        run: echo corrio el job 1 y el job 2   

