name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  steps:
    -uses:    
      job1:
        name: primero
      job2:
        name: segundo