name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

