name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
  job2:
    runs-on: ubuntu-latest
    needs: job1 
    run: echo corrio el job 1 y el job 2   

