name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Tirate un job 1
        run: echo job 1
  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Tirate un job 2
        run: echo job 2  

  job3:
    runs-on: ubuntu-latest
    needs: job2

    steps:
      - name: Tirate un job 3
        run: echo job 3         

