name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
         
      - name: Setup node
        uses: action/setup-node@v3
        whit: 
          node-version: 16.13.x
          cache: npm

      -name: Install
       run: npm ci    